init_config:

instances:
  - host: "%%env_REDIS_HOST%%"
    port: "%%env_REDIS_PORT%%"
    ssl: false
    tags:
      - env:%%env_DD_ENV%%
      - service:ticket-queue-redis
      - component:queue-redis
      - managed:false
